### ISSUE TITLE
Tests failing in master

### ISSUE THREAD

**Issue by sahilshekhawat** [pydy/pydy#162]
Two of the tests are failling in current master.
```
======================================================================
FAIL: pydy.codegen.tests.test_ode_function_generator.TestODEFunctionGeneratorSubclasses.test_rhs_args
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sahil/anaconda/envs/pydy-dev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/sahil/pydy/pydy/codegen/tests/test_ode_function_generator.py", line 362, in test_rhs_args
    np.testing.assert_allclose(xdot, last_xdot)
  File "/home/sahil/anaconda/envs/pydy-dev/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/sahil/anaconda/envs/pydy-dev/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([ 0.099968,  0.050154,  0.4285  ,  0.618715, -0.436786, -2.954496,
        0.790694,  0.003718])
 y: array([ 0.099968,  0.050154,  0.4285  ,  0.618715, -0.549453, -1.488752,
        0.501619,  0.026753])

======================================================================
FAIL: pydy.tests.test_utils.test_sympy_equal_to_or_newer_than
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sahil/anaconda/envs/pydy-dev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/sahil/pydy/pydy/tests/test_utils.py", line 9, in test_sympy_equal_to_or_newer_than
    assert sympy_equal_to_or_newer_than('0.7.6', '0.7.6-git')
AssertionError

----------------------------------------------------------------------

```

**Comment by moorepants** [comment]
The first error is interesting and needs to be investigated. The second one is simply because we only support setuptools<8 at the moment. See issue #120.

**Comment by moorepants** [comment]
@sahilshekhawat Can you confirm the first error? If it is still an error what versions of all of the dependencies do you have?

**Comment by sahilshekhawat** [comment]
Yes, its still there with the latest master. Here's all the packages and their versions.
```
cairo                     1.12.18                       3  
cython                    0.22                     py27_0  
fastcache                 1.0.2                    py27_0  
flake8                    2.3.0                    py27_0  
fontconfig                2.11.1                        3  
freetype                  2.5.2                         1  
ipython                   3.1.0                    py27_0  
ipython-notebook          3.1.0                    py27_1  
jinja2                    2.7.3                    py27_1  
jsonschema                2.4.0                    py27_0  
libpng                    1.5.13                        1  
libsodium                 0.4.5                         0  
libxml2                   2.9.0                         0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_1  
mccabe                    0.3                      py27_1  
mistune                   0.5.1                    py27_1  
nose                      1.3.6                    py27_0  
numpy                     1.9.2                    py27_0  
openssl                   1.0.1k                        1  
pep8                      1.6.2                    py27_0  
pixman                    0.26.2                        0  
ptyprocess                0.4                      py27_0  
py2cairo                  1.10.0                   py27_2  
pyflakes                  0.8.1                    py27_0  
pygments                  2.0.2                    py27_0  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_1  
python                    2.7.9                         3  
python-dateutil           2.4.2                    py27_0  
pytz                      2015.2                   py27_0  
pyzmq                     14.6.0                   py27_0  
qt                        4.8.6                         2  
readline                  6.2                           2  
scipy                     0.15.1               np19py27_0  
setuptools                15.2                     py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
sympy                     0.7.6                    py27_0  
system                    5.8                           2  
terminado                 0.5                      py27_0  
theano                    0.7.0                np19py27_0  
tk                        8.5.18                        0  
tornado                   4.1                      py27_0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  

```

**Comment by moorepants** [comment]
Ok, I reproduced it. I was using SymPy master but it is failing on SymPy 0.7.6. That was the only difference in my dev setup.
