### ISSUE TITLE
Travis builds are broken

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#304]
See: https://travis-ci.org/pydy/pydy/jobs/98552493

**Comment by moorepants** [comment]
```
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=corei7-avx -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mno-tbm -mavx -msse4.2 -msse4.1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=46080 -mtune=generic -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/numpy/core/include -I/home/travis/miniconda/envs/test-env/include/python2.7 -o /home/travis/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-wheezy-sid-x86_64-2.7.11-64/tmpW89YEe/6a98a5d7526794b8ec4e5d09f0998656.so /home/travis/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-wheezy-sid-x86_64-2.7.11-64/tmpW89YEe/mod.cpp -L/home/travis/miniconda/envs/test-env/lib -lpython2.7
ERROR
pydy.codegen.tests.test_ode_function_generator.TestODEFunctionGeneratorSubclasses.test_init_doc ... ok
pydy.codegen.tests.test_ode_function_generator.TestODEFunctionGeneratorSubclasses.test_old_rhs_args ... ok
pydy.codegen.tests.test_ode_function_generator.TestODEFunctionGeneratorSubclasses.test_rhs_args ... ok
pydy.viz.tests.test_scene.TestScene.test_clear_trajectories ... ok
pydy.viz.tests.test_scene.TestScene.test_create_static_html ... ok
pydy.viz.tests.test_scene.TestScene.test_custom_camera ... ok
pydy.viz.tests.test_scene.TestScene.test_generate_scene_dict ... ok
pydy.viz.tests.test_scene.TestScene.test_generate_simulation_dict ... ok
pydy.viz.tests.test_scene.TestScene.test_generate_visualization_json_system ... ok
pydy.viz.tests.test_scene.TestScene.test_init ... ok
pydy.viz.tests.test_scene.TestScene.test_setting_incompatible_attrs ... ok
pydy.viz.tests.test_shapes.test_shape ... ok
pydy.viz.tests.test_shapes.test_shape_geometry_with_expressions ... ok
pydy.viz.tests.test_shapes.test_cube ... ok
pydy.viz.tests.test_shapes.test_cylinder ... ok
pydy.viz.tests.test_shapes.test_cone ... ok
pydy.viz.tests.test_shapes.test_sphere ... ok
pydy.viz.tests.test_shapes.test_circle ... ok
pydy.viz.tests.test_shapes.test_plane ... ok
pydy.viz.tests.test_shapes.test_tetrahedron ... ok
pydy.viz.tests.test_shapes.test_octahedron ... ok
pydy.viz.tests.test_shapes.test_icosahedron ... ok
pydy.viz.tests.test_shapes.test_torus ... ok
pydy.viz.tests.test_shapes.test_tube ... ok
pydy.viz.tests.test_shapes.test_torus_knot ... ok
pydy.viz.tests.test_visualization_frame_scene.TestVisualizationFrameScene.test_numeric_transform ... ok
pydy.viz.tests.test_visualization_frame_scene.TestVisualizationFrameScene.test_orthographic_camera ... ok
pydy.viz.tests.test_visualization_frame_scene.TestVisualizationFrameScene.test_perspective_camera ... ok
pydy.viz.tests.test_visualization_frame_scene.TestVisualizationFrameScene.test_point_light ... ok
pydy.viz.tests.test_visualization_frame_scene.TestVisualizationFrameScene.test_scene_init ... ok
pydy.viz.tests.test_visualization_frame_scene.TestVisualizationFrameScene.test_vframe_with_particle ... ok
pydy.viz.tests.test_visualization_frame_scene.TestVisualizationFrameScene.test_vframe_with_rbody ... ok
pydy.viz.tests.test_visualization_frame_scene.TestVisualizationFrameScene.test_vframe_with_rframe ... ok
pydy.viz.tests.test_visualization_frame_scene.TestVisualizationFrameScene.test_vframe_without_name ... ok
pydy.tests.test_models.test_multi_mass_spring_damper ... ok
pydy.tests.test_models.test_multi_mass_spring_damper_with_forces ... ok
pydy.tests.test_models.test_multi_mass_spring_damper_double ... ok
pydy.tests.test_system.TestSystem.test_constants ... ok
pydy.tests.test_system.TestSystem.test_coordinates ... ok
pydy.tests.test_system.TestSystem.test_generate_ode_function ... ok
pydy.tests.test_system.TestSystem.test_init ... ok
pydy.tests.test_system.TestSystem.test_initial_conditions ... ok
pydy.tests.test_system.TestSystem.test_integrate ... ok
pydy.tests.test_system.TestSystem.test_ode_solver ... ok
pydy.tests.test_system.TestSystem.test_specifieds ... ok
pydy.tests.test_system.TestSystem.test_speeds ... ok
pydy.tests.test_system.TestSystem.test_states ... ok
pydy.tests.test_utils.test_sympy_equal_to_or_newer_than ... ok
pydy.tests.test_utils.test_codegen_linewrap ... ok

======================================================================
ERROR: pydy.codegen.tests.test_ode_function_generator.TestODEFunctionGeneratorSubclasses.test_generate_with_specifieds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pydy/pydy/pydy/codegen/tests/test_ode_function_generator.py", line 228, in test_generate_with_specifieds
    f = g.generate()
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 759, in generate
    self.generate_full_mass_matrix_function()
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 964, in generate_full_mass_matrix_function
    f = self._theanoize(outputs)
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 932, in _theanoize
    mode=theano.Mode(linker='c'))
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/sympy/printing/theanocode.py", line 229, in theano_function
    return theano.function(tinputs, toutputs, **theano_kwargs)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/compile/function_module.py", line 1466, in orig_function
    defaults)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/compile/function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/gof/cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/gof/cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/gof/cc.py", line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1076, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/gof/cc.py", line 1354, in compile_cmodule
    preargs=preargs)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2010, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ("Compilation failed (return status=1): /tmp/cciZ5sVQ.s: Assembler messages:. /tmp/cciZ5sVQ.s:7761: Error: no such instruction: `vfmsub312sd (%rax),%xmm3,%xmm4'. ", '[Join(TensorConstant{0}, TensorConstant{[[1 0 0 0 0 0]]}, TensorConstant{[[0 1 0 0 0 0]]}, TensorConstant{[[0 0 1 0 0 0]]}, InplaceDimShuffle{x,0}(MakeVector(TensorConstant{0.0}, TensorConstant{0.0}, TensorConstant{0.0}, Elemwise{add,no_inplace}(m0, m1, m2), *1 -> Elemwise{Composite{((i0 * i1 * i2 * i3) + (i0 * i1 * i4 * i3))}}[(0, 3)](TensorConstant{-1.0}, l0, m1, *5 -> Elemwise{sin,no_inplace}(q1_t), m2), *8 -> Elemwise{Mul}[(0, 3)](TensorConstant{-1.0}, l1, m2, *7 -> Elemwise{sin,no_inplace}(q2_t)))), InplaceDimShuffle{x,0}(MakeVector(TensorConstant{0.0}, TensorConstant{0.0}, TensorConstant{0.0}, *1, Elemwise{Composite{((i0 * sqr(i1)) + (i2 * sqr(i1)))}}(m1, l0, m2), *9 -> Elemwise{Composite{(i0 * i1 * i2 * ((i3 * i4) + (i5 * i6)))}}[(0, 3)](l0, l1, m2, *3 -> Elemwise{cos,no_inplace}(q1_t), *2 -> Elemwise{cos,no_inplace}(q2_t), *5, *7))), InplaceDimShuffle{x,0}(MakeVector(TensorConstant{0.0}, TensorConstant{0.0}, TensorConstant{0.0}, *8, *9, Elemwise{Composite{(i0 * sqr(i1))}}(m2, l1)))), Join(TensorConstant{0}, InplaceDimShuffle{x,0}(MakeVector(u0_t)), InplaceDimShuffle{x,0}(MakeVector(u1_t)), InplaceDimShuffle{x,0}(MakeVector(u2_t)), InplaceDimShuffle{x,0}(MakeVector(Elemwise{Composite{((i0 * i1 * i2 * i3) + (i0 * i4 * i2 * i3) + (i5 * i4 * i6 * i7) + i8)}}(l0, m1, *4 -> Elemwise{sqr,no_inplace}(u1_t), *3, m2, l1, *6 -> Elemwise{sqr,no_inplace}(u2_t), *2, F_t))), InplaceDimShuffle{x,0}(MakeVector(Elemwise{Composite{((-i0) + (i1 * i2 * i3 * i4 * i5) + (i1 * i2 * i3 * i6 * i5) + (i3 * i7 * i6 * i8 * ((i5 * i9) + (i1 * i10 * i11))) + i12)}}[(0, 8)](T2_t, TensorConstant{-1.0}, g, l0, m1, *3, m2, l1, *6, *7, *2, *5, T1_t))), InplaceDimShuffle{x,0}(MakeVector(Elemwise{Composite{((i0 * i1 * i2 * i3 * i4) + (i5 * i2 * i3 * i6 * ((i4 * i7) + (i0 * i8 * i9))) + i10)}}[(0, 6)](TensorConstant{-1.0}, g, l1, m2, *2, l0, *4, *5, *3, *7, T2_t))))]')
-------------------- >> begin captured stdout << ---------------------
===============================
===============================
/tmp/cciZ5sVQ.s: Assembler messages:
/tmp/cciZ5sVQ.s:7761: Error: no such instruction: `vfmsub312sd (%rax),%xmm3,%xmm4'


--------------------- >> end captured stdout << ----------------------

Name                                      Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------
pydy.py                                       1      0   100%   
pydy/codegen.py                               1      0   100%   
pydy/codegen/c_code.py                      119      7    94%   92, 220-227
pydy/codegen/code.py                         16      3    81%   15-17, 30
pydy/codegen/cython_code.py                  91      6    93%   200, 203, 223-224, 226-227
pydy/codegen/ode_function_generators.py     399     10    97%   5, 329, 341-342, 383, 773, 847-849, 902, 1010
pydy/models.py                               89      1    99%   162
pydy/system.py                              205     14    93%   142, 151, 326-329, 358, 477-478, 481-482, 563, 588, 607
pydy/utils.py                                44      4    91%   52, 77-80
pydy/version.py                               1      0   100%   
pydy/viz.py                                  19      0   100%   
pydy/viz/camera.py                          139     11    92%   112-113, 142, 157, 172, 225-226, 344, 358, 405-406
pydy/viz/light.py                            56      6    89%   97-98, 130, 139, 189-190
pydy/viz/scene.py                           341    129    62%   28, 37-46, 152, 165, 178, 191-192, 222, 228-232, 248-251, 258-263, 278-282, 288-291, 299-303, 315-318, 361-369, 397-398, 414, 419-420, 464, 491-494, 532-535, 573-581, 586, 592, 596-598, 615-616, 619-623, 629, 633-637, 644-676, 682-689, 694-698, 710-752
pydy/viz/server.py                           69     50    28%   14-16, 28-30, 33-39, 42, 45-52, 75-77, 81-101, 104-106, 117-123
pydy/viz/shapes.py                          107      2    98%   202-204
pydy/viz/visualization_frame.py             124     17    86%   7, 96, 116-117, 129, 132, 148, 167, 183, 203, 233-238, 328, 392-393
-----------------------------------------------------------------------
TOTAL                                      1821    260    86%   
----------------------------------------------------------------------
Ran 72 tests in 85.991s

FAILED (errors=1)
travis_time:end:039bc19c:start=1450891159412185145,finish=1450891245819936075,duration=86407750930
[0K
[31;1mThe command "nosetests -v --with-coverage --cover-package=pydy" exited with 1.[0m
travis_time:start:0b1efe8c
[0K$ cd pydy/viz/static/js/tests && phantomjs run-jasmine.js SpecRunner.html

Started
[PyDy INFO]: initializing Visualizer[PyDy ALERT]: Incompatible browser![32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[PyDy INFO]: initializing Visualizer[PyDy ALERT]: Incompatible browser![PyDy INFO]: Activated UI controls[PyDy INFO]: Loading scene JSON file:sample_data/scene_desc.json[32m.[0m[PyDy INFO]: initializing Visualizer[PyDy ALERT]: Incompatible browser![PyDy INFO]: Activated UI controls[PyDy INFO]: Loading scene JSON file:sample_data/scene_desc.json[32m.[0m[PyDy INFO]: Ajax request completed, adding Objects to scene[PyDy INFO]: Ajax request completed, adding Objects to scene
[32m.[0m[PyDy INFO]: Ajax request completed, adding Objects to scene[32m.[0m[PyDy INFO]: Ajax request completed, adding Objects to scene[32m.[0m[PyDy INFO]: Ajax request completed, adding Objects to scene[32m.[0m[PyDy INFO]: Ajax request completed, adding Objects to scene[32m.[0m[PyDy INFO]: Ajax request completed, adding Objects to scene[32m.[0m[PyDy INFO]: Ajax request completed, adding Objects to scene[32m.[0m[PyDy INFO]: Ajax request completed, adding Objects to scene[PyDy INFO]: Ajax request completed, adding Objects to scene[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m

20 specs, 0 failures
Finished in 8.068 seconds
```

@oliverlee

**Comment by oliverlee** [comment]
Seems that some wrong compiler flags are set. See this similar issue: https://github.com/Theano/Theano/issues/1980

Do we set those anywhere? Or maybe the Travis hardware changed?

**Comment by moorepants** [comment]
The Travis hardware may have changed. They have some blog posts about trying to change to new VMs.

**Comment by moorepants** [comment]
Maybe this is a fix: https://github.com/Theano/Theano/issues/3780

**Comment by moorepants** [comment]
That seemed to fix things. Note that Travis has switched to new hardware for the legacy precise builds.

> This job ran on our new platform for Legacy Precise builds. Please read our blog post for more information.
