### ISSUE TITLE
Theano code gen now balks a large numbers of inputs

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#344]
This is a numpy ufunc limitation and it seems we are hitting it with the theano_function generator. This may be a sympy issue more than a pydy one.

Running the benchmark in bin gives this for 7 and above links:

```
Pendulum with 7 links.
======================
The derivation took 2.43710 seconds.

Generating with lambdify method.
--------------------------------
The code generation took 0.38180 seconds.
ODE integration took 52.97012 seconds.

Generating with theano method.
------------------------------
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f5282762a90>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/pydy/codegen/ode_function_generators.py", line 999, in generate_ode_function
    g = generator(*args, **kwargs)
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/theano/gof/opt.py", line 196, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/theano/gof/opt.py", line 82, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/theano/tensor/opt.py", line 5499, in apply
    new_outputs = self.optimizer(node)
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/theano/tensor/opt.py", line 5434, in local_fuse
    n = OP(C)(*inputs).owner
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/theano/tensor/elemwise.py", line 496, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 36 and outputs = 1)

The code generation took 17.50953 seconds.
 lsoda--  at current t (=r1), mxstep (=i1) steps   
       taken on this call before reaching tout     
      in above message,  i1 =       500
      in above message,  r1 =  0.8364696299189D+01
/home/moorepants/miniconda3/lib/python3.5/site-packages/scipy/integrate/odepack.py:218: ODEintWarning: Excess work done on this call (perhaps wrong Dfun type). Run with full_output = 1 to get quantitative information.
  warnings.warn(warning_msg, ODEintWarning)
ODE integration took 6.68611 seconds.

Generating with cython method.
------------------------------
The code generation took 2.67844 seconds.
ODE integration took 3.35109 seconds.
```

**Comment by oliverlee** [comment]
I get some sort of compilation error with Theano for 7 links (works for 2 links).

**Comment by moorepants** [comment]
Theano is now deprecated.
