### ISSUE TITLE
line 370 in "pydy/pydy/codegen/ode_function_generators.py" why use "c" as an index?

### ISSUE THREAD

**Issue by GitYiheng** [pydy/pydy#394]
TypeError: list indices must be integers or slices, not Symbol

After making the following modification, the error disappears.
"self._constants_values[i] = p[c]" - > "self._constants_values[i] = p[i]"

My question is why "c" is used as an index in p[c]? Is my modification make sense?

Thanks,
Yiheng

**Comment by moorepants** [comment]
Please provide a minimal example that exhibits the error. Paste in your code and the resulting traceback.

Here is the code:

```python
    def _convert_constants_dict_to_array(self, p):
        """Returns an array of numerical values from the constants
        dictionary in the correct order."""

        # NOTE : It's unfortunate that this has to be run at every rhs eval,
        # because subsequent calls to rhs() doesn't require different
        # constants. I suppose you can sub out all the constants in the EoMs
        # before passing them into the generator. That would beg for the
        # capability to support self.constants=None to skip all of this
        # stuff in the rhs eval.
        for i, c in enumerate(self.constants):
            self._constants_values[i] = p[c]

return self._constants_values

    def _parse_constants(self, *args):
        """Returns an ndarray containing the numerical values of the
        constants in the correct order. If the constants are already an
        array, that array is returned."""

        p = args[-1]
        try:
            p = self._convert_constants_dict_to_array(p)
        except IndexError:
            # p is an array so just return the args
            return args
        else:
            return args[:-1] + (p,)
```

Maybe the code doesn't raise and IndexError for newer versions of NumPy/SymPy, etc.

**Comment by GitYiheng** [comment]
Hi moorepants,

I'm working on a n-link pendulum simulation in OpenAI Gym format (code included in README.md):
https://github.com/GitYiheng/gym-multipendulum

The problem is that the arguments passed to self._convert_constants_dict_to_array(p) is a list of symbols rather than constants. But I'm not very experienced with this kind of problem. Here is the traceback:

```bash
Traceback (most recent call last):
  File "test10_env_test.py", line 15, in <module>
    observation, reward, done, _ = env.step(action)
  File "/home/yh/repo/gym-multipendulum/gym_multipendulum/envs/multipendulum_env.py", line 300, in step
    self.x = odeint(self.right_hand_side, self.x, self.dt_step, args=(action, self.numerical_constants))[-1]
  File "/home/yh/venv/lib/python3.5/site-packages/scipy/integrate/odepack.py", line 215, in odeint
    ixpr, mxstep, mxhnil, mxordn, mxords)
  File "/home/yh/venv/lib/python3.5/site-packages/pydy/codegen/ode_function_generators.py", line 476, in rhs
    args = self._parse_all_args(*args)
  File "/home/yh/venv/lib/python3.5/site-packages/pydy/codegen/ode_function_generators.py", line 431, in _parse_all_args
    args = self._parse_constants(*args)
  File "/home/yh/venv/lib/python3.5/site-packages/pydy/codegen/ode_function_generators.py", line 385, in _parse_constants
    p = self._convert_constants_dict_to_array(p)
  File "/home/yh/venv/lib/python3.5/site-packages/pydy/codegen/ode_function_generators.py", line 373, in _convert_constants_dict_to_array
    self._constants_values[i] = p[c]
TypeError: list indices must be integers or slices, not Symbol
```

Thanks,
Yiheng

**Comment by moorepants** [comment]
pydy is expecting a numpy array, note the IndexError, seems like you might be passing in a list, which returns a TypeError. pydy can be adjusted to handle both, but there may be some slow downs associated with that.

**Comment by moorepants** [comment]
FYI:

```
In [3]: import numpy as np

In [4]: a = np.ones(20)

In [5]: a['a']
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-8c8059950d02> in <module>()
----> 1 a['a']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
> <ipython-input-5-8c8059950d02>(1)<module>()
----> 1 a['a']

ipdb>                                                                                                                                                                                                              


In [6]: a = ['a', 'b', 'c']

In [7]: a['too']
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-916879dc9807> in <module>()
----> 1 a['too']

TypeError: list indices must be integers or slices, not str
> <ipython-input-7-916879dc9807>(1)<module>()
----> 1 a['too']
```

**Comment by GitYiheng** [comment]
I see. Thanks moorepants!
