### ISSUE TITLE
The System class should automatically take care of dynamicsymbols._t

### ISSUE THREAD

**Issue by NikhilPappu** [pydy/pydy#396]
Consider this example:
```
m, k, b, g=sm.symbols('m k b g', real=True)
position, speed = me.dynamicsymbols('position speed')
positiond, speedd = me.dynamicsymbols('position speed', 1)
o = me.dynamicsymbols('o')
force = o*sm.sin(me.dynamicsymbols._t)
frame_ceiling=me.ReferenceFrame('ceiling')
point_origin=me.Point('origin')
point_origin.set_vel(frame_ceiling, 0)
particle_block=me.Particle('block', me.Point('block_pt'), sm.Symbol('m'))
particle_block.point.set_pos(point_origin, position*frame_ceiling.x)
particle_block.mass = m
particle_block.point.set_vel(frame_ceiling, speed*frame_ceiling.x)
force_magnitude = m*g-k*position-b*speed+force
force_block = (force_magnitude*frame_ceiling.x).subs({positiond:speed})
kd_eqs = [positiond - speed]
forceList = [(particle_block.point,(force_magnitude*frame_ceiling.x).subs({positiond:speed}))]
kane = me.KanesMethod(frame_ceiling, q_ind=[position], u_ind=[speed], kd_eqs = kd_eqs)
fr, frstar = kane.kanes_equations([particle_block], forceList)
zero = fr+frstar
from pydy.system import System
sys = System(kane, constants = {m:1.0, k:1.0, b:0.2, g:9.8},
specifieds={me.dynamicsymbols._t:lambda x, t: t, o:2},
initial_conditions={position:0.1, speed:-1*1.0},
times = np.linspace(0.0, 10.0, 10.0/0.01))

y=sys.integrate()
```

Here we have `force = o*sm.sin(me.dynamicsymbols._t)`. In the simulation code using the System class, passing `dynamicsymbols._t` as a specified throws an error:

```
Traceback (most recent call last):
  File "C:\Users\pappu\Desktop\Diving_Into_SymPy\autolev-test-examples\pydy-example-repo\mass_spring_damper.py", line 29, in <module>
    times = np.linspace(0.0, 10.0, 10.0/0.01))
  File "C:\Users\pappu\Desktop\virtual_env\env\lib\site-packages\pydy\system.py", line 116, in __init__
    self.specifieds = specifieds
  File "C:\Users\pappu\Desktop\virtual_env\env\lib\site-packages\pydy\system.py", line 249, in specifieds
    self._check_specifieds(specifieds)
  File "C:\Users\pappu\Desktop\virtual_env\env\lib\site-packages\pydy\system.py", line 306, in _check_specifieds
    self._assert_is_specified_symbol(k, symbols)
  File "C:\Users\pappu\Desktop\virtual_env\env\lib\site-packages\pydy\system.py", line 261, in _assert_is_specified_symbol
    symbol))
ValueError: Symbol t is not a 'specified' symbol.
```
Instead if `dynamicsymbols('t')` is used (which is just a regular dynamicsymbol) in both the places mentioned above, the code works but this isn't an ideal change.
One could just pass in `force` itself as a specified and this would work just fine but it would be nice if cases like these work as well.

A convenient feature that can be added to fix this is to let the System class directly substitute time stamps in any stray `dynamicsymbols._t` occurrences in the kane's equations.

**Comment by moorepants** [comment]
This is a duplicate of #133 I believe.

**Comment by NikhilPappu** [comment]
@moorepants Yeah they are essentially the same.
