### ISSUE TITLE
Code generation tests are failing because only a single element of the array is computed

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#403]
```
======================================================================
FAIL: pydy.codegen.tests.test_ode_function_generator.TestODEFunctionGeneratorSubclasses.test_generate_full_rhs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pydy/pydy/pydy/codegen/tests/test_ode_function_generator.py", line 225, in test_generate_full_rhs
    self.eval_rhs(rhs_func)
  File "/home/travis/build/pydy/pydy/pydy/codegen/tests/test_ode_function_generator.py", line 204, in eval_rhs
    np.testing.assert_allclose(xdot, expected_xdot)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 1452, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0
(mismatch 50.0%)
 x: array(2.)
 y: array([ 2.      , -1.333333])
======================================================================
FAIL: pydy.codegen.tests.test_ode_function_generator.TestODEFunctionGeneratorSubclasses.test_generate_with_specifieds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pydy/pydy/pydy/codegen/tests/test_ode_function_generator.py", line 316, in test_generate_with_specifieds
    np.testing.assert_allclose(xdot, expected)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 1452, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0
(mismatch 83.3333333333%)
 x: array(0.0476)
 y: array([ 0.0476  ,  0.494714,  0.864781,  0.599996, -2.601222,  3.405213])
```

**Comment by moorepants** [comment]
This is due to the theano issue #404.

**Comment by moorepants** [comment]
This issue is raised over at sympy: https://github.com/sympy/sympy/issues/14986

**Comment by moorepants** [comment]
This has been fixed in sympy master.
