### ISSUE TITLE
problem installing with pip3 on ubuntu 18.04

### ISSUE THREAD

**Issue by mitkof6** [pydy/pydy#414]
I am getting the following error message when installing pydy through pip3 on ubuntu:18.04

Downloading https://files.pythonhosted.org/packages/68/61/c55f9a56297f4301aa01a2ff88208f6c603d11e4b2284162089ad96b1f43/pydy-0.5.0.tar.gz (5.3MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1ogsh1v6/pydy/setup.py", line 30, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 11725: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1ogsh1v6/pydy/
The command '/bin/sh -c pip3 install pydy' returned a non-zero code: 1

**Comment by moorepants** [comment]
Looks like our `setup.py` might not be Python 3 compatible.

**Comment by moorepants** [comment]
`setup.py` runs fine in the latest CI builds with Python 3.6: https://travis-ci.org/pydy/pydy/jobs/479119452

I'll have to check manually.

**Comment by moorepants** [comment]
These run without error for me in Py 3.6:
```
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: with open('README.rst', 'r') as f: 
   ...:     txt = f.read() 
   ...:                                                                                                  

In [2]: txt = open('README.rst').read()                                                                  
```

**Comment by moorepants** [comment]
Can you report which version of pip you are using?

**Comment by mitkof6** [comment]
Hi,

I am not getting the same behavior on archlinux or ubuntu 18.04 which I tested. This happens only when I try to build a docker from file. This is part of the configuration file:
 
`FROM ubuntu:18.04

# required for tzdata
ENV DEBIAN_FRONTEND=noninteractive

# install ubuntu packages
RUN apt-get update && apt-get -y upgrade && apt-get -y \
install imagemagick python3 python3-pip cython libgmp-dev \
lrslib git python3-tk liblapack-dev freeglut3-dev libxi-dev \
libxmu-dev doxygen swig python-dev g++ openjdk-11-jdk \
cmake-curses-gui tzdata nano wget
RUN alias python=python3

# setup timezone
RUN ln -fs /usr/share/zoneinfo/Europe/Athens /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata

# setup python dependencies
RUN pip3 install --upgrade pip
RUN pip3 install scipy numpy sympy pandas seaborn matplotlib \
tqdm multipolyfit regex jupyter pycddlib
RUN pip3 --version
RUN pip3 install pydy  # problem with pydy for python3
`

I tried updating pip3 (v 19.2.3), but the error still occurs. Thanks for your time.

**Comment by moorepants** [comment]
You could download with wget and then install with `python setup.py install` to see if that works.

**Comment by mitkof6** [comment]
Yes, I tried this also without success.

**Comment by moorepants** [comment]
Can you patch the setup.py file with:

```
        long_description=open('README.rst', encoding='utf-8').read(),
````

and see if that works?

**Comment by moorepants** [comment]
I haven't been able to reproduce this. Reopen if there is more info.
