### ISSUE TITLE
Tests fail against `sympy` 1.10

### ISSUE THREAD

**Issue by risicle** [pydy/pydy#465]
Hi,

In maintaining the Nix package for `pydy`, we noticed that when we bumped our sympy version from 1.9 -> 1.10.1 `pydy` 0.6.0's tests started failing.

```
FAILED pydy/codegen/tests/test_c_code.py::TestCMatrixGenerator::test_generate_cse
FAILED pydy/codegen/tests/test_c_code.py::TestCMatrixGenerator::test_generate_code_blocks
FAILED pydy/codegen/tests/test_c_code.py::TestCMatrixGenerator::test_doprint
FAILED pydy/codegen/tests/test_octave_code.py::test_OctaveMatrixGenerator - A...
```

Full output is available at https://hydra.nixos.org/log/fsa3xzags44jyi27inh17f1s5q7pcshf-python3.9-pydy-0.6.0.drv. This happens on macos & linux, python 3.9 & 3.10.

It looks as though the tests are simply relying too much on very specific results coming from sympy:

```
>           assert g.doprint() == expected_m_file_1p2
E           AssertionError: assert 'function [ou...12];\n\nend\n' == 'function [ou...10];\n\nend\n'
E             Skipping 395 identical leading characters in diff, use -v to show
E             +  pydy_5 = -input_3(9);
E             -  pydy_5 = input_3(9).*pydy_4;
E             ?       ^
E             +     pydy_6 = input_3(9).*pydy_4;
E             ? +++      ^
E             -     pydy_6 = input_3(9) - pydy_3.*pydy_5;...
E             
E             ...Full output truncated (40 lines hidden), use '-vv' to show
```

**Comment by moorepants** [comment]
Thanks for the issue. Yes, these tests have been problematic. I may have an open issue about converting them to only numerical checks. It will take some effort to do that, which I probably won't have until later in the summer.

**Comment by moorepants** [comment]
These are the test failures seen with SymPy 1.11.1:
```
======================================================================
FAIL: pydy.codegen.tests.test_c_code.TestCMatrixGenerator.test_doprint
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moorepants/miniconda/envs/pydy-dev/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moorepants/src/pydy/pydy/codegen/tests/test_c_code.py", line 1001, in test_doprint
    assert source == '\n'.join(lines[:1] + lines[2:])
AssertionError

======================================================================
FAIL: pydy.codegen.tests.test_c_code.TestCMatrixGenerator.test_generate_code_blocks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moorepants/miniconda/envs/pydy-dev/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moorepants/src/pydy/pydy/codegen/tests/test_c_code.py", line 553, in test_generate_code_blocks
    assert v == expected[k]
AssertionError

======================================================================
FAIL: pydy.codegen.tests.test_c_code.TestCMatrixGenerator.test_generate_cse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moorepants/miniconda/envs/pydy-dev/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moorepants/src/pydy/pydy/codegen/tests/test_c_code.py", line 177, in test_generate_cse
    assert self.generator.subexprs == expected_subexprs
AssertionError

======================================================================
FAIL: pydy.codegen.tests.test_octave_code.test_OctaveMatrixGenerator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moorepants/miniconda/envs/pydy-dev/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moorepants/src/pydy/pydy/codegen/tests/test_octave_code.py", line 145, in test_OctaveMatrixGenerator
    assert g.doprint() == expected_m_file_1p2
AssertionError

----------------------------------------------------------------------
```
