### ISSUE TITLE
nose tests don't run

### ISSUE THREAD

**Issue by beew** [pydy/pydy#490]
nose is deprecated and the tests no longer run in python 3.10

```
nosetests
Traceback (most recent call last):
  File "/home/bernard/opt/python310/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/home/bernard/opt/python310/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/home/bernard/opt/python310/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/bernard/opt/python310/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/home/bernard/opt/python310/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/home/bernard/opt/python310/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/home/bernard/opt/python310/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/bernard/opt/python310/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/bernard/opt/python310/lib/python3.10/site-packages/nose/loader.py", line 454, in loadTestsFromName
    return LazySuite(
  File "/home/bernard/opt/python310/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/home/bernard/opt/python310/lib/python3.10/unittest/suite.py", line 22, in __init__
    self._tests = []
  File "/home/bernard/opt/python310/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
```

collections.Callable is replaced by collections.abc.Callable.

OS is ubuntu 22.04.

**Comment by moorepants** [comment]
We run the tests with Python 3.7 to 3.11 in the CI with nose with no errors. So I'm not sure why you are hitting an issue.

**Comment by beew** [comment]
Ok. It runs now after uninstalling nose and installing a maintained fork nose-py3 https://github.com/atsb/nose-py3/tags

Please update your documentation. nose-1.3.7 doesn't work and it is dead.

**Comment by moorepants** [comment]
You'll have to provide more information. The last release of nose works fine in our tests, so I don't know what is the cause of the error you are seeing.

> Please update your documentation or switch to pytest. nose-1.3.7 doesn't work and it is dead.

I am happy to review a pull request to switch to pytest.

**Comment by Sigmanificient** [comment]
Hi, I am a contributor to nixpkgs (nix package repository), and we are currently in a process of removing nose dependency. I tried to make a patch for `pydy`:
```diff
diff --git a/pydy/codegen/tests/test_c_code.py b/pydy/codegen/tests/test_c_code.py
index 24b6784..5af9287 100644
--- a/pydy/codegen/tests/test_c_code.py
+++ b/pydy/codegen/tests/test_c_code.py
@@ -2,9 +2,10 @@
 
 import os
 
+import pytest
+
 from pkg_resources import parse_version
 import sympy as sm
-from nose.tools import assert_raises
 
 from ...models import multi_mass_spring_damper
 from ..c_code import CMatrixGenerator
@@ -40,7 +41,8 @@ class TestCMatrixGenerator():
         # Make sure an error is risen if not enough arguments are provided.
         arguments = self.arguments[:-1]
 
-        assert_raises(ValueError, CMatrixGenerator, arguments, self.matrices)
+        with pytest.raises(ValueError):
+            CMatrixGenerator(arguments, self.matrices)
 
     def test_generate_cse(self):
 
diff --git a/pydy/tests/test_utils.py b/pydy/tests/test_utils.py
index cc27c81..4b2bf9f 100644
--- a/pydy/tests/test_utils.py
+++ b/pydy/tests/test_utils.py
@@ -1,8 +1,9 @@
 #!/usr/bin/env python
 
+import pytest
+
 from pkg_resources import parse_version
 from setuptools import __version__ as SETUPTOOLS_VERSION
-from nose.tools import assert_raises
 
 from sympy import cos, sin, tan, sqrt, Matrix
 from sympy.physics.mechanics import dynamicsymbols
@@ -20,7 +21,7 @@ def test_sympy_equal_to_or_newer_than():
     assert sympy_equal_to_or_newer_than('0.6.5', '0.7.6.dev')
     assert not sympy_equal_to_or_newer_than('0.7.7', '0.7.6.dev')
     if parse_version(SETUPTOOLS_VERSION) >= parse_version('8.0'):
-        with assert_raises(ValueError):
+        with pytest.raises(ValueError):
             sympy_equal_to_or_newer_than('0.7.7', '0.7.6-git')
 
 
diff --git a/pydy/viz/tests/test_scene.py b/pydy/viz/tests/test_scene.py
index 9bb4c83..1673a64 100644
--- a/pydy/viz/tests/test_scene.py
+++ b/pydy/viz/tests/test_scene.py
@@ -4,11 +4,12 @@ import os
 import shutil
 import glob
 
+import pytest
+
 import numpy as np
 from numpy.testing import assert_allclose
 from sympy import symbols
 import sympy.physics.mechanics as me
-from nose.tools import assert_raises
 
 from ...system import System
 from ..shapes import Sphere
@@ -129,13 +130,13 @@ class TestScene(object):
         scene = Scene(self.ref_frame, self.origin, self.viz_frame,
                       times=self.sys.times)
 
-        with assert_raises(ValueError):
+        with pytest.raises(ValueError):
             scene.system = self.sys
 
         scene = Scene(self.ref_frame, self.origin, self.viz_frame,
                       system=self.sys)
 
-        with assert_raises(ValueError):
+        with pytest.raises(ValueError):
             scene.times = self.sys.times
 
     def test_clear_trajectories(self):
diff --git a/pydy/viz/tests/test_shapes.py b/pydy/viz/tests/test_shapes.py
index 767e0ce..487e061 100644
--- a/pydy/viz/tests/test_shapes.py
+++ b/pydy/viz/tests/test_shapes.py
@@ -2,9 +2,11 @@
 
 # external
 import numpy as np
+import pytest
+
 from sympy import symbols
 from numpy.testing import assert_allclose
-from nose.tools import assert_raises
+
 try:
     import pythreejs as p3js
 except ImportError:
@@ -29,19 +31,19 @@ def test_shape():
 
     shape.name = 'shape1'
     assert shape.name == 'shape1'
-    with assert_raises(TypeError):
+    with pytest.raises(TypeError):
         shape.name = 1
 
     shape.color = 'red'
     assert shape.color == 'red'
-    with assert_raises(ValueError):
+    with pytest.raises(ValueError):
         shape.color = 'puke'
 
     shape.material = "water"
     assert shape.material == "water"
     shape.material = "WATER"
     assert shape.material == "WATER"
-    with assert_raises(ValueError):
+    with pytest.raises(ValueError):
         shape.material = 'fluffy cloth'
 
     assert shape.generate_dict() == {"color": "red",
diff --git a/setup.py b/setup.py
index 0e230d6..5aeaacf 100644
--- a/setup.py
+++ b/setup.py
@@ -50,7 +50,7 @@ setup(
     packages=find_packages(),
     install_requires=install_requires,
     extras_require=extras_require,
-    tests_require=['nose>=1.3.7'],
+    tests_require=['pytest'],
     test_suite='nose.collector',
     include_package_data=True,
     classifiers=[
```

However there is many failling tests: 
```
=================================== test session starts ===================================
platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/sigmanificient/pydy
collected 71 items                                                                        

pydy/codegen/tests/test_c_code.py FFFFFFFFF                                         [ 12%]
pydy/codegen/tests/test_cython_code.py FFFF.                                        [ 19%]
pydy/codegen/tests/test_octave_code.py .                                            [ 21%]
pydy/codegen/tests/test_ode_function_generator.py ...FFFF..FFF...                   [ 42%]
pydy/tests/test_models.py ...                                                       [ 46%]
pydy/tests/test_system.py FFFFFFFFFFF.                                              [ 63%]
pydy/tests/test_utils.py ...                                                        [ 67%]
pydy/viz/tests/test_scene.py FFFFFFFF                                               [ 78%]
pydy/viz/tests/test_shapes.py ...............                                       [100%]

======================================== FAILURES =========================================
...
======================= 39 failed, 32 passed, 3 warnings in 35.88s ========================
```
