### ISSUE TITLE
Errors using System.integrate

### ISSUE THREAD

**Issue by madz-mit** [pydy/pydy#501]
I am trying to perform numerical simulation of a simplified version of the quadcopter code from [bobzwik/Quadcopter_SimCon](https://github.com/bobzwik/Quadcopter_SimCon) . The simplifications include removing the 4 motors and all the forces and moments associated with them while retaining gravity (So it's basically a rock in free-fall with 6 degrees of freedom). But I'm getting errors using sys.integrate().
The following is my modified code

```python
from sympy import symbols
from sympy.physics.mechanics import *
import numpy as np
from pydy.system import System

# Reference frames and Points
# ---------------------------
N = ReferenceFrame('N')  # Inertial Frame
B = ReferenceFrame('B')  # Drone after X (roll) rotation (Final rotation)
C = ReferenceFrame('C')  # Drone after Y (pitch) rotation
D = ReferenceFrame('D')  # Drone after Z (yaw) rotation (First rotation)

No = Point('No')
Bcm = Point('Bcm')  # Drone's center of mass


# Variables
# ---------------------------
# x, y and z are the drone's coordinates in the inertial frame, expressed with the inertial frame
# u, v and w are the drone's velocities in the inertial frame, expressed with the drone's frame
# phi, theta and psi represents the drone's orientation in the inertial frame, expressed with a ZYX Body rotation
# p, q and r are the drone's angular velocities in the inertial frame, expressed with the drone's frame

x, y, z, u, v, w = dynamicsymbols('x y z u v w')
phi, theta, psi, p, q, r = dynamicsymbols('phi theta psi p q r')

# First derivatives of the variables
xd, yd, zd, ud, vd, wd = dynamicsymbols('x y z u v w', 1)
phid, thetad, psid, pd, qd, rd = dynamicsymbols('phi theta psi p q r', 1)

# Constants
# ---------------------------
mB, g, IBxx, IByy, IBzz = symbols('mB g IBxx IByy IBzz')

# Rotation ZYX Body
# ---------------------------
D.orient(N, 'Axis', [psi, N.z])
C.orient(D, 'Axis', [theta, D.y])
B.orient(C, 'Axis', [phi, C.x])

# Origin
# ---------------------------
No.set_vel(N, 0)

# Translation
# ---------------------------
Bcm.set_pos(No, x*N.x + y*N.y + z*N.z)
Bcm.set_vel(N, u*B.x + v*B.y + w*B.z) 


# Inertia Dyadic
# ---------------------------
IB = inertia(B, IBxx, IByy, IBzz)

# Create Bodies
# ---------------------------
BodyB = RigidBody('BodyB', Bcm, B, mB, (IB, Bcm))
BodyList = [BodyB]

# Forces and Torques
# ---------------------------
Grav_Force = (Bcm, mB*g*N.z)


ForceList = [Grav_Force]

# Kinematic Differential Equations
# ---------------------------
kd = [xd - dot(Bcm.vel(N), N.x), yd - dot(Bcm.vel(N), N.y), zd - dot(Bcm.vel(N), N.z), p - dot(B.ang_vel_in(N), B.x), q - dot(B.ang_vel_in(N), B.y), r - dot(B.ang_vel_in(N), B.z)]

# Kane's Method
# ---------------------------
KM = KanesMethod(N, q_ind=[x, y, z, phi, theta, psi], u_ind=[u, v, w, p, q, r], kd_eqs=kd)
(fr, frstar) = KM.kanes_equations(BodyList, ForceList)

initial_conditions = {x:0.0, y:0.0, z:-1000.0, phi:0.0, theta:0.0, psi:0.0, u:0.0, v:0.0, w:0.0, p:0.0, q:0.0, r:0.0}
constants = {mB:1.0,g:9.81, IBxx:1.0, IByy:1.0, IBzz:1.0}
times = np.linspace(0, 5, 100)

sys = System(KM,initial_conditions=initial_conditions,constants=constants,times=times)
#sys.generate_ode_function(generator='cython')
sys.integrate()
``` 

And the error I'm getting (Running on ipython notebook) :

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py", line 907, in generate_ode_function
    g = generator(*args, **kwargs)

TypeError: 'str' object is not callable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-3375dfdba49d>", line 82, in <module>
    sys.integrate()

  File "/usr/local/lib/python3.7/dist-packages/pydy/system.py", line 521, in integrate
    self.generate_ode_function()

  File "/usr/local/lib/python3.7/dist-packages/pydy/system.py", line 483, in generate_ode_function
    **kwargs)

  File "/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py", line 917, in generate_ode_function
    return g.generate()

  File "/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py", line 622, in generate
    self.generate_full_mass_matrix_function()

  File "/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py", line 781, in generate_full_mass_matrix_function
    f = self._lambdify(outputs)

  File "/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py", line 760, in _lambdify
    cse=self._options['cse'])

  File "/usr/local/lib/python3.7/dist-packages/sympy/utilities/lambdify.py", line 900, in lambdify
    c = compile(funcstr, filename, 'exec')

  File "<lambdifygenerated-2>", line 45
    x43 =   # Not supported in Python with numpy:
                                                 ^
SyntaxError: invalid syntax
``` 

If I uncomment the line before sys.integrate() for using the cython generator I get a different error :
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py in generate_ode_function(*args, **kwargs)
    906         # See if user passed in a custom class.
--> 907         g = generator(*args, **kwargs)
    908     except TypeError:

TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-14-f40aa1090680> in <module>
----> 1 sys.generate_ode_function(generator='cython')
      2 sys.integrate()

/usr/local/lib/python3.7/dist-packages/pydy/system.py in generate_ode_function(self, **kwargs)
    481         self._evaluate_ode_function = generate_ode_function(
    482             *self._args_for_gen_ode_func(),
--> 483             **kwargs)
    484 
    485         return self.evaluate_ode_function

/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py in generate_ode_function(*args, **kwargs)
    915             raise NotImplementedError(msg)
    916         else:
--> 917             return g.generate()
    918     else:
    919         return g.generate()

/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py in generate(self)
    620             self.generate_full_rhs_function()
    621         elif self.system_type == 'full mass matrix':
--> 622             self.generate_full_mass_matrix_function()
    623         elif self.system_type == 'min mass matrix':
    624             self.generate_min_mass_matrix_function()

/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py in generate_full_mass_matrix_function(self)
    698                                                                   self.inputs))
    699         else:
--> 700             self._set_eval_array(self._cythonize(outputs, self.inputs))
    701 
    702     def generate_min_mass_matrix_function(self):

/usr/local/lib/python3.7/dist-packages/pydy/codegen/ode_function_generators.py in _cythonize(self, outputs, inputs)
    651         g = CythonMatrixGenerator(inputs, outputs,
    652                                   prefix=self._options['prefix'],
--> 653                                   cse=self._options['cse'])
    654         return g.compile(tmp_dir=self._options['tmp_dir'],
    655                          verbose=self._options['verbose'])

/usr/local/lib/python3.7/dist-packages/pydy/codegen/cython_code.py in __init__(self, arguments, matrices, prefix, cse)
     91         self.num_arguments = len(arguments)
     92         self.c_matrix_generator = CMatrixGenerator(arguments, matrices,
---> 93                                                    cse=cse)
     94 
     95         self._generate_code_blocks()

/usr/local/lib/python3.7/dist-packages/pydy/codegen/matrix_generator.py in __init__(self, arguments, matrices, cse)
     61             if required_arg not in all_arguments:
     62                 msg = "{} is missing from the argument sequences."
---> 63                 raise ValueError(msg.format(required_arg))
     64 
     65         self.matrices = matrices

ValueError: Derivative(phi(t), t) is missing from the argument sequences.
```

But I am able to run the astrobee example from pydy, which is also a 6DoF model with 6 coordinates and 6 speeds all in the same reference frame.

I am suspecting that the error is due to the combined usage of different reference frames while defining coordinates and speeds in the kane's model. For the coordinates vector, the positions (x,y,z) are in the NED frame, attitudes are euler angles (phi, theta, psi), while for the speeds vector, the velocities (u,v,w) are in the Body FRD frame and angular rates (p,q,r) are also in the Body FRD frame. This is common practice in flight simulation. See for example Page 11 (Section 1.2 Non- linear state equations, Eq 1-15 to 1-19) of the document "Derivation and Definition
of a Linear Aircraft Model" (https://ntrs.nasa.gov/api/citations/19890005752/downloads/19890005752.pdf) Thus we don't have x'=u, y'=v and so on. Is my understanding correct? And how would I solve this problem? Note that the equations derived using Kane's method appear to be correct. Or am I missing something?

**Comment by Peter230655** [comment]
I just had a quick look.
in this line: constants = {mB:1.0,g:9.81, IBxx:1.0, IByy:1.0, IBzz:1.0}
I do not find the constants: dxm, dym, dzm. 
As you use them, they must be specified.

**Comment by madz-mit** [comment]
Appreciate the quick response. I have commented the portions using dxm, dym and dzm. The code runs correctly till sys.integrate. I have inspected the KM object, fr and frstar. They seem ok. I'll try to clean up the markdown so that the code is clear. From the first error message, it looks like the compile function has run into a syntax error while processing the output of lambdify ?

**Comment by madz-mit** [comment]
The dxm dym dzm parameters are used to model the quad motor torques. I have discarded those and only kept gravity.

**Comment by Peter230655** [comment]
Could you give your latest code?
I will try it this evening.
What I often find helpful:
Look for the symbols and the dynamic symbols in fr and frstar like
me.find_dynamicsymbols(fr + frstar)
(fr + frstar).free_symbols

This may help to see whether you have specified everything before you integrate numerically.

**Comment by madz-mit** [comment]
Here is the cleaned up code from the referred repository https://github.com/bobzwik/Quadcopter_SimCon. 
The exact file I have used from that repository is  PyDy Scripts/00 - Basic/Quad_3D_uvw/Quad_3D_frd_NED_Euler_uvw.py 
and edited as I have explained i.e. removed all motors and their forces and torques. I was expecting to simulate a freefall for a start and then move on to other tests.

```python
from sympy import symbols
from sympy.physics.mechanics import *
import numpy as np
from pydy.system import System

# Reference frames and Points
# ---------------------------
N = ReferenceFrame('N')  # Inertial Frame
B = ReferenceFrame('B')  # Drone after X (roll) rotation (Final rotation)
C = ReferenceFrame('C')  # Drone after Y (pitch) rotation
D = ReferenceFrame('D')  # Drone after Z (yaw) rotation (First rotation)

No = Point('No')
Bcm = Point('Bcm')  # Drone's center of mass


# Variables
# ---------------------------
# x, y and z are the drone's coordinates in the inertial frame, expressed with the inertial frame
# u, v and w are the drone's velocities in the inertial frame, expressed with the drone's frame
# phi, theta and psi represents the drone's orientation in the inertial frame, expressed with a ZYX Body rotation
# p, q and r are the drone's angular velocities in the inertial frame, expressed with the drone's frame

x, y, z, u, v, w = dynamicsymbols('x y z u v w')
phi, theta, psi, p, q, r = dynamicsymbols('phi theta psi p q r')

# First derivatives of the variables
xd, yd, zd, ud, vd, wd = dynamicsymbols('x y z u v w', 1)
phid, thetad, psid, pd, qd, rd = dynamicsymbols('phi theta psi p q r', 1)

# Constants
# ---------------------------
mB, g, IBxx, IByy, IBzz = symbols('mB g IBxx IByy IBzz')

# Rotation ZYX Body
# ---------------------------
D.orient(N, 'Axis', [psi, N.z])
C.orient(D, 'Axis', [theta, D.y])
B.orient(C, 'Axis', [phi, C.x])

# Origin
# ---------------------------
No.set_vel(N, 0)

# Translation
# ---------------------------
Bcm.set_pos(No, x*N.x + y*N.y + z*N.z)
Bcm.set_vel(N, u*B.x + v*B.y + w*B.z) 


# Inertia Dyadic
# ---------------------------
IB = inertia(B, IBxx, IByy, IBzz)

# Create Bodies
# ---------------------------
BodyB = RigidBody('BodyB', Bcm, B, mB, (IB, Bcm))
BodyList = [BodyB]

# Forces and Torques
# ---------------------------
Grav_Force = (Bcm, mB*g*N.z)


ForceList = [Grav_Force]

# Kinematic Differential Equations
# ---------------------------
kd = [xd - dot(Bcm.vel(N), N.x), yd - dot(Bcm.vel(N), N.y), zd - dot(Bcm.vel(N), N.z), p - dot(B.ang_vel_in(N), B.x), q - dot(B.ang_vel_in(N), B.y), r - dot(B.ang_vel_in(N), B.z)]

# Kane's Method
# ---------------------------
KM = KanesMethod(N, q_ind=[x, y, z, phi, theta, psi], u_ind=[u, v, w, p, q, r], kd_eqs=kd)
(fr, frstar) = KM.kanes_equations(BodyList, ForceList)

initial_conditions = {x:0.0, y:0.0, z:-1000.0, phi:0.0, theta:0.0, psi:0.0, u:0.0, v:0.0, w:0.0, p:0.0, q:0.0, r:0.0}
constants = {mB:1.0,g:9.81, IBxx:1.0, IByy:1.0, IBzz:1.0}
times = np.linspace(0, 5, 100)

sys = System(KM,initial_conditions=initial_conditions,constants=constants,times=times)
#sys.generate_ode_function(generator='cython')
sys.integrate()
``` 
The KM.mass_matrix_full and KM.forcing_full, after substitution and simplification are shown below, which appear to be correct as per reference material (You can check Lecture 4 of https://ocw.mit.edu/courses/16-333-aircraft-stability-and-control-fall-2004/)
![CodeOutput](https://github.com/pydy/pydy/assets/29753065/2a7dbe4d-4edc-4c99-8604-5fecb78c32a0)

**Comment by Peter230655** [comment]
I took your program of this morning, and just 'cleaned it up' very slightly. I pasted it below.
I have no idea what you are trying to calculate, but the program runs without error.

NB: 
I was told, it is not good practice to write: ..... import *
Common is to write
import sympy as sm
inport sympy.physics.mechanics as sm

and then write e.g.
a = np.cos(x)
b = sm.cos(x)
N = me.Point('N')
 

```
from sympy import symbols
from sympy.physics.mechanics import *
import numpy as np
from pydy.system import System
#Reference frames and Points

N = ReferenceFrame('N') # Inertial Frame
B = ReferenceFrame('B') # Drone after X (roll) rotation (Final rotation)
C = ReferenceFrame('C') # Drone after Y (pitch) rotation
D = ReferenceFrame('D') # Drone after Z (yaw) rotation (First rotation)

t = dynamicsymbols._t

No = Point('No')
Bcm = Point('Bcm') # Drone's center of mass
M1 = Point('M1') # Motor 1 is front left, then the rest increments CW (Drone is in X configuration, not +)
M2 = Point('M2')
M3 = Point('M3')
M4 = Point('M4')
#Variables

#x, y and z are the drone's coordinates in the inertial frame, expressed with the inertial frame
#u, v and w are the drone's velocities in the inertial frame, expressed with the drone's frame
#phi, theta and psi represents the drone's orientation in the inertial frame, expressed with a ZYX Body rotation
#p, q and r are the drone's angular velocities in the inertial frame, expressed with the drone's frame
x, y, z, u, v, w = dynamicsymbols('x y z u v w')
phi, theta, psi, p, q, r = dynamicsymbols('phi theta psi p q r')

#First derivatives of the variables
xd, yd, zd, ud, vd, wd = dynamicsymbols('x y z u v w', 1)
phid, thetad, psid, pd, qd, rd = dynamicsymbols('phi theta psi p q r', 1)
#Constants

mB, g, dxm, dym, dzm, IBxx, IByy, IBzz = symbols('mB g dxm dym dzm IBxx IByy IBzz')
ThrM1, ThrM2, ThrM3, ThrM4, TorM1, TorM2, TorM3, TorM4 = symbols('ThrM1 ThrM2 ThrM3 ThrM4 TorM1 TorM2 TorM3 TorM4')
mB, g, IBxx, IByy, IBzz = symbols('mB g IBxx IByy IBzz')
#Rotation ZYX Body

D.orient(N, 'Axis', [psi, N.z])
C.orient(D, 'Axis', [theta, D.y])
B.orient(C, 'Axis', [phi, C.x])
#Origin

No.set_vel(N, 0)
#Translation

Bcm.set_pos(No, x*N.x + y*N.y + z*N.z)
Bcm.set_vel(N, u*B.x + v*B.y + w*B.z)
#Motor placement
#M1 is front left, then clockwise numbering
#dzm is positive for motors above center of mass

M1.set_pos(Bcm, dxm*B.x - dym*B.y - dzm*B.z)
M2.set_pos(Bcm, dxm*B.x + dym*B.y - dzm*B.z)
M3.set_pos(Bcm, -dxm*B.x + dym*B.y - dzm*B.z)
M4.set_pos(Bcm, -dxm*B.x - dym*B.y - dzm*B.z)
M1.v2pt_theory(Bcm, N, B)
M2.v2pt_theory(Bcm, N, B)
M3.v2pt_theory(Bcm, N, B)
M4.v2pt_theory(Bcm, N, B)
#Inertia Dyadic

IB = inertia(B, IBxx, IByy, IBzz)
#Create Bodies

BodyB = RigidBody('BodyB', Bcm, B, mB, (IB, Bcm))
BodyList = [BodyB]
#Forces and Torques

Grav_Force = (Bcm, mB*g*N.z)
FM1 = (M1, -ThrM1*B.z)
FM2 = (M2, -ThrM2*B.z)
FM3 = (M3, -ThrM3*B.z)
FM4 = (M4, -ThrM4*B.z)

TM1 = (B, -TorM1*B.z)
TM2 = (B, TorM2*B.z)
TM3 = (B, -TorM3*B.z)
TM4 = (B, TorM4*B.z)
ForceList = [Grav_Force, FM1, FM2, FM3, FM4, TM1, TM2, TM3, TM4]
#ForceList = [Grav_Force]
#Kinematic Differential Equations

kd = [xd - dot(Bcm.vel(N), N.x), yd - dot(Bcm.vel(N), N.y), zd - dot(Bcm.vel(N), N.z), p - dot(B.ang_vel_in(N), B.x), q - dot(B.ang_vel_in(N), B.y), r - dot(B.ang_vel_in(N), B.z)]
#Kane's Method

KM = KanesMethod(N, q_ind=[x, y, z, phi, theta, psi], u_ind=[u, v, w, p, q, r], kd_eqs=kd)
(fr, frstar) = KM.kanes_equations(BodyList, ForceList)
print('fr + frstar DS', find_dynamicsymbols(fr + frstar))
print('fr + frstar FS', (fr + frstar).free_symbols)

initial_conditions = {x:0.0, y:0.0, z:-1000.0, phi:0.0, theta:0.0, psi:0.0, u:0.0, v:0.0, w:0.0, p:0.0, q:0.0, r:0.0}
constants = {mB:1.0,g:9.81, IBxx:1.0, IByy:1.0, IBzz:1.0}
times = np.linspace(0, 5, 100)

sys = System(KM,initial_conditions=initial_conditions,constants=constants,times=times)
sys.generate_ode_function(generator='cython')
sys.integrate()
```

**Comment by madz-mit** [comment]
Could you try my updated code also? If your code is running, I expect that if you plot the output of sys.integrate, the z and w states should correspond to height and velocity in free fall from 1000m with all other states 0. But I'm confused because you seem to have put back all the terms from the original code, but left them out in the constants dictionary.

**Comment by Peter230655** [comment]
_But I'm confused because you seem to have put back all the terms from the original code, but left them out in the constants dictionary._
I wondered myself, but since I did not see them in the output of _(fr + frstar).free_symbols_ they do not seem to be there.
I did not check, why they do not seem to be there. This is part of your modeling a system, that is mechanics.
As I understand this forum, it is about problems with _pydy_, not about how to model a given system using KanesMethod.
But I can say this with confidence: I have made more than 100 different simulations with KanesMethod - and if I modeled the system correctly, the result invariably was correct.

**Comment by madz-mit** [comment]
I had tried my code on several machines (both Win and Linux) with no success. I just tried it now on Google's colab online just to see if they have any updated versions of any dependencies etc. But no joy. I get the same error. 

Even if I paste your code, I get the same error. This error is copied as it is from colab :
```
fr + frstar DS {Derivative(phi(t), t), Derivative(u(t), t), u(t), phi(t), Derivative(w(t), t), Derivative(v(t), t), theta(t), Derivative(theta(t), t), p(t), Derivative(r(t), t), q(t), Derivative(p(t), t), r(t), v(t), Derivative(q(t), t), w(t)}
fr + frstar FS {IByy, TorM2, ThrM1, dxm, g, ThrM4, TorM1, IBzz, IBxx, TorM3, ThrM2, mB, ThrM3, dym, t, TorM4}
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/pydy/codegen/ode_function_generators.py", line 907, in generate_ode_function
    g = generator(*args, **kwargs)

TypeError: 'str' object is not callable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-13-25d1802f6f73>"](https://localhost:8080/#), line 98, in <cell line: 98>
    sys.integrate()

  File "/usr/local/lib/python3.10/dist-packages/pydy/system.py", line 521, in integrate
    self.generate_ode_function()

  File "/usr/local/lib/python3.10/dist-packages/pydy/system.py", line 481, in generate_ode_function
    self._evaluate_ode_function = generate_ode_function(

  File "/usr/local/lib/python3.10/dist-packages/pydy/codegen/ode_function_generators.py", line 917, in generate_ode_function
    return g.generate()

  File "/usr/local/lib/python3.10/dist-packages/pydy/codegen/ode_function_generators.py", line 622, in generate
    self.generate_full_mass_matrix_function()

  File "/usr/local/lib/python3.10/dist-packages/pydy/codegen/ode_function_generators.py", line 781, in generate_full_mass_matrix_function
    f = self._lambdify(outputs)

  File "/usr/local/lib/python3.10/dist-packages/pydy/codegen/ode_function_generators.py", line 759, in _lambdify
    return sm.lambdify(vec_inputs, outputs, modules=modules,

  File "/usr/local/lib/python3.10/dist-packages/sympy/utilities/lambdify.py", line 903, in lambdify
    c = compile(funcstr, filename, 'exec')

  File "<lambdifygenerated-2>", line 45
    x43 =   # Not supported in Python with numpy:
            ^
SyntaxError: invalid syntax
```  
You can see the output of your 2 prints here. But then the same error is thrown

**Comment by Peter230655** [comment]
I am sorry, but this completely out of my expertise! Maybe somebody else can help.
I use Jupyter notebooks on Visual Studio Code on a windows PC.
Sorry!

**Comment by moorepants** [comment]
I think the issue is that you have derivatives in your forcing vector:

```
In [11]: me.find_dynamicsymbols(KM.forcing)
Out[11]: 
{Derivative(phi(t), t),
 Derivative(theta(t), t),
 p(t),
 phi(t),
 q(t),
 r(t),
 theta(t),
 u(t),
 v(t),
 w(t)}
```

**Comment by moorepants** [comment]
These lines fix it for me:

```
Bcm.set_acc(N, msubs(Bcm.acc(N), solve(kd, (xd, yd, zd, phid, thetad, psid))))
B.set_ang_vel(N, msubs(B.ang_vel_in(N), solve(kd, (xd, yd, zd, phid, thetad, psid))))
```

**Comment by moorepants** [comment]
Also here is a drone example that may be of interest: https://opty.readthedocs.io/latest/examples/plot_drone.html#sphx-glr-examples-plot-drone-py

**Comment by Peter230655** [comment]
> I think the issue is that you have derivatives in your forcing vector:
> 
> ```
> In [11]: me.find_dynamicsymbols(KM.forcing)
> Out[11]: 
> {Derivative(phi(t), t),
>  Derivative(theta(t), t),
>  p(t),
>  phi(t),
>  q(t),
>  r(t),
>  theta(t),
>  u(t),
>  v(t),
>  w(t)}
> ```

Strange, that my slightly modified program of madz-mit ran fine with me, but not for madz-mit. Also, unless I made a mistake, #26751 did not raise a problem with me. I ran both on Jupyter notebook.

**Comment by moorepants** [comment]
The derivatives will not show up in `KanesMethod.forcing` if you use SymPy >= 1.13 (not yet released).

**Comment by madz-mit** [comment]
> These lines fix it for me:
> 
> ```
> Bcm.set_acc(N, msubs(Bcm.acc(N), solve(kd, (xd, yd, zd, phid, thetad, psid))))
> B.set_ang_vel(N, msubs(B.ang_vel_in(N), solve(kd, (xd, yd, zd, phid, thetad, psid))))
> ```

Yes. It works for me too now with these changes. Thanks!
Will look out for the version upgrade.
