### ISSUE TITLE
Tests should run even if optional dependencies are not installed

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#52]
If I don't have cython installed, I get this error when running the tests:

```
======================================================================
ERROR: pydy.codegen.tests.test_code.TestCode.test_generate_ode_function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moorepants/src/pydy/pydy/codegen/tests/test_code.py", line 72, in test_generate_ode_function
    specified, generator=backend)
  File "/home/moorepants/src/pydy/pydy/codegen/code.py", line 400, in generate_ode_function
    cython_module = importlib.import_module(filename_prefix)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named multibody_system

======================================================================
ERROR: pydy.codegen.tests.test_code.TestCode.test_generate_ode_function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 384, in tearDown
    try_run(self.inst, ('teardown', 'tearDown'))
  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 469, in try_run
    return func()
  File "/home/moorepants/src/pydy/pydy/codegen/tests/test_code.py", line 113, in teardown
    shutil.rmtree('build')
  File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: 'build'
```

**Comment by oliverlee** [comment]
Fixed here: https://github.com/pydy/pydy/commit/d7c415c0d9bd4215018df370beacb8a935c6e1d2
